### ISSUE TITLE
Make `msg_send` automatically convert `BOOL` to `bool`

### ISSUE THREAD

**Issue by ArturKovacs** [madsmtm/objc2#125]
As far as I understand, one always has to specify `BOOL` instead of `bool` as the return type of messages. This is error prone.

But objc doesn't have the `bool` type, so it seems like a safe assumption that whenever the return (or parameter) type is specified as `bool` it should instead be `BOOL`. With this assumption, `msg_send` could do the conversion internally. 

Right now we have to write
```rust
let my_var: BOOL = msg_send![my_object, my_method];
if my_var.as_bool() {
    // stuff
}
```

But it would be much safer if we could write the following, and `msg_send` would do the correct conversion automatically.
```rust
let my_var = msg_send![my_object, my_method];
if my_var {
    // stuff
}
```

**Comment by madsmtm** [comment]
I like the idea, though I don't really think it's possible?

`msg_send!` effectively desugars to a generic function call (generic over both return type and arguments):
```rust
let my_var = msg_send![my_object, my_method];
if my_var {}

// Effectively becomes

let my_var = MessageReceiver::send_message(my_object, sel!(my_method), ());
if my_var {}
```

Somehow we would have to put a conversion step in there, an idea could be like this:
```rust
pub trait IntoBoolIfBool {
    type BoolType;
    fn into_bool_if_bool(self) -> Self::BoolType;
}

impl IntoBoolIfBool for runtime::Bool {
    type BoolType = bool;
    fn into_bool_if_bool(self) -> Self::BoolType {
        self.as_bool()
    }
}

impl IntoBoolIfBool for i32 {
    type BoolType = i32;
    fn into_bool_if_bool(self) -> Self::BoolType {
        self
    }
}

let my_var = MessageReceiver::send_message(my_object, sel!(my_method), ());
let my_var_converted = IntoBoolIfBool::into_bool_if_bool(my_var);
if my_var_converted {}
```

But since we can't tell the type system that there is only one implementor of `IntoBoolIfBool` that returns `bool`, the type of `my_var` would probably still have to be annotated?

Other solutions (that I think would be possible):
1. Disallow returning `bool` from `msg_send!`.
  
    If we still want to allow passing `bool` as a parameter, this would require a new `trait EncodeReturn: Encode` (related to https://github.com/madsmtm/objc2/issues/118) for types that can safely be constructed from Objective-C (note: I'm reluctant to add too many new traits, since it means downstream library creators have more traits to implement; but this one _may_ be worth it).
2. Add `msg_send_bool!` helper method that simply does the desired conversion.

**Comment by madsmtm** [comment]
Actually, while writing this it occurs to me: We could flip the `IntoBoolIfBool` trait to `FromBoolIfBool`:
```rust
pub trait FromBoolIfBool: Sized {
    type BoolType;
    fn from_bool_if_bool(arg: Self::BoolType) -> Self;
}

impl FromBoolIfBool for bool {
    type BoolType = runtime::Bool;
    fn from_bool_if_bool(arg: Self::BoolType) -> Self {
        arg.as_bool()
    }
}

impl FromBoolIfBool for i32 {
    type BoolType = i32;
    fn from_bool_if_bool(arg: Self::BoolType) -> Self {
        arg
    }
}

let my_var = MessageReceiver::send_message(my_object, sel!(my_method), ());
let my_var_converted = FromBoolIfBool::from_bool_if_bool(my_var);
if my_var_converted {}
```

Which would actually work!

Now, I still think we would have to figure out a nice solution that doesn't require the user to implement `FromBoolIfBool` (god I wish `#[feature(specialization)]` was here!)

**Comment by madsmtm** [comment]
It should also be noted that Objective-C methods are not _required_ to use `BOOL`, they could be using the standard C99 `_Bool`; so we may have to provide an escape hatch (though very, _very_ infrequently used)

**Comment by madsmtm** [comment]
I went with `msg_send_bool!` for now, seemed like a good enough way to solve it, may change things up later (e.g. when `#[feature(specialization)]` hits)
