### ISSUE TITLE
Allow deregistering classes?

### ISSUE THREAD

**Issue by madsmtm** [madsmtm/objc2#251]
Pulled out from https://github.com/madsmtm/objc2/issues/30.

It could be interesting to allow deregistering dynamically declared classes!

Idea:
```rust
struct ClassBuilder { ... }

impl ClassBuilder {
    fn add_method(...)
    fn add_property(...)
    // ...
    fn build(self, ...) -> OwnedClass { ... }
}

impl OwnedClass {
    fn leak(self) -> &'static Class { ... }
}

// Would deallocate the class
impl Drop for OwnedClass { ... }

impl Deref<Target = Class> for OwnedClass { ... }
impl DerefMut<Target = Class> for OwnedClass { ... }

impl Class {
    fn to_str;
    // Is it possible to mutate classes after they've been registered?
    fn add_method(&mut self, ...)
}
```

Primary motivation is better testing, but also stuff like `winit`'s `NSApplicationDelegate`/`NSWindowDelegate` subclasses could change the size of it's ivars based on the size of passed in closures? (To store the closures in the delegate instead of boxing them beforehand).

Very difficult to do safely though, since we _must_ ensure that there are not instances to the class left (and probably also that there are no `&Class` pointers to the class left?). Maybe the lifetime of the class would need to somehow propagate to the objects?
```rust
struct CustomObject<'c> { ... }

impl<'c> ClassType for CustomObject<'c> {
    fn class() -> ?
}
```

Also not really supported on GNUStep.

**Comment by notgull** [comment]
On Windows, with window classes, my strategy is to use the strategy you referenced; having the class's lifetime propagate to the object.

**Comment by madsmtm** [comment]
I think my biggest problem is that it would make `objc2::runtime::Class::get` `unsafe` (and by extension, the `class!` macro), since there's no lifetime to tie the class to.

I may still change it at some point, once raw `class!`/`Class::get` usage is rarer due to people using `icrate` / the helper macros `declare_class!` & `extern_class!`.

**Comment by madsmtm** [comment]
I think I'm going to make a decision on this one: If people want to deregister classes, then they can do so themselves fairly easily with `objc2::ffi::objc_disposeClassPair`, but we're not going to provide any conveniences to do so, since it'll simply complicate the rest of the API too much.

(Even more so since all of Apple's frameworks also assume that classes are static, so it'd need even more work there to make it sound).
