### ISSUE TITLE
The deal with mutability

### ISSUE THREAD

**Issue by madsmtm** [madsmtm/objc2#265]
I was [once convinced](https://github.com/SSheldon/rust-objc/issues/112#issuecomment-1139443814) that we could restrict mutation to `&mut self` methods, but after [having battled with AppKit](https://github.com/rust-windowing/winit/pull/2465) and seen how Swift does it, I'm beginning to doubt that this is the best way.

`NSString` is immutable while `NSMutableString` is, naturally, mutable. Since our current implementation only allows mutation of `NSMutableString` through `&mut self`, it is safe to make both of these `Send + Sync`; all is well and Rusty.

Now, remember that `&NSMutableString -> &NSString` and `Id<NSMutableString, O> -> Id<NSString, O>` is safe - so if we were to make mutation of `NSMutableString` possible through `&self`, not only would `NSMutableString` be `!Sync`, but so would `NSString`! (They could still be `Send`, that would simply allow moving them via. `Id<T, Owned>` to a different thread - quite similar to `std::cell::Cell`)

That's the primary downside: Our objects can no longer be shared across threads. Downsides that usually apply to Rust code (aliasing optimizations, ...) are void in our case, since `NSString` is already `UnsafeCell`.

On the other hand, if we were to remove mutability we could:
1. Make `NSArray<T>`, `NSDictionary<K, V>` and such collection types simpler
2. Since most frameworks use interior mutability and/or are not thread safe anyhow, the usage of the Foundation framework would match the usage of these.
3. It would be possible for users to inherit `NSString`, without them having to ensure that their object was `Sync`
4. `Id::retain` could be made safe(r?)
5. [automatic](https://github.com/madsmtm/objc2/pull/264) [bindings](https://github.com/madsmtm/objc2/issues/85) would be simpler
6. Using `NSMutableString` inside a `declare_class!` that is not meant to be thread-safe anyhow is easier (e.g. means we won't have to use `&mut` in `winit`)

So... Yeah, will think about this a bit, but I think we may have to sacrifice being able to use Objective-C classes across threads (exactly the same compromise Swift does, their `String` is `Sendable` but `NSString` is not).

**Comment by madsmtm** [comment]
https://github.com/rust-windowing/winit/pull/2457 highlighted an issue: We'd have to return `Id<WinitView, Owned>` if we wanted to make `accepts_first_mouse` mutable after the fact - but you can very rarely have an owned view (because other code may hold references to it, unknown to you), so this would be a footgun.

**Comment by madsmtm** [comment]
Instead, making it `Id<WinitView, Shared>` and then contain `accepts_first_mouse: Cell<bool>` would be more correct.

Note that this is not currently possible because the layout of `Cell` is not guaranteed, will request this from `std` at some point.

**Comment by madsmtm** [comment]
Even ignoring thread safety, a problem arises with methods that return references to internal data. For example, the following fails at compile-time because `set_bytes` requires `&mut self`, but if we were to change things to no longer require mutable pointers, it would cause UB:
```rust
let mut data = NSMutableData::with_bytes(b"abc");
let b = data.bytes();
data.set_bytes(b"def");
assert_eq!(b, b"abc");
```

Similarly for `-[NSString UTF8String]`, other methods annotated with `NS_RETURNS_INNER_POINTER`, and probably also the collection types - perhaps also when iterating?

Swift "solves" this by just returning `UnsafeRawPointer`. When iterating over `Array`, they make a local copy; when iterating over `NSMutableArray`, they don't, so memory safety is quite easy to violate:
```rust
import Foundation
var arr = NSMutableArray(array: [1, 2, 3])
for elem in arr {
    arr.add(4)
    print("test", elem)
}
```

So yeah, I'm quite conflicted as to how we should do mutability; perhaps things will be clearer once I've done more of #264, and get to see if there are parts other than Foundation that would benefit from mutability.

**Comment by madsmtm** [comment]
Another solution: Just keep every mutating method `unsafe`

**Comment by madsmtm** [comment]
Would maybe make sense to take the `Ownership` parameter from `NSCopying` and move it to `ClassType`?

**Comment by notgull** [comment]
Truth be told, I'm fine with having a standard class that's `!Send/!Sync` and then having an escape-hatch `unsafe` adaptor that is `Send/Sync`. In the wide variety of cases, these types end up being thread-unsafe anyhow.

**Comment by madsmtm** [comment]
Yeah if it was only thread safety that was the issue, then I would agree, but as noted in https://github.com/madsmtm/objc2/issues/265#issuecomment-1267747513, that still won't allow us to make mutating methods like `addObject:` safe

**Comment by madsmtm** [comment]
A bit unsure where the `MainThreadMarker` argument is most convenient to put? As the first argument (after `self`, if present), or as the last one?

E.g. the difference between these two:
```rust
// As first
let window = NSWindow::initWithContentRect_styleMask_backing_defer(
    NSWindow::alloc(),
    MainThreadMarker::new(),
    NSRect::new(0.0, 0.0),
    NSWindowStyleMaskClosable
    | NSWindowStyleMaskMiniaturizable
    | NSWindowStyleMaskResizable
    | NSWindowStyleMaskTitled,
    NSBackingStoreBuffered,
    false,
);
// As last
let window = NSWindow::initWithContentRect_styleMask_backing_defer(
    NSWindow::alloc(),
    NSRect::new(0.0, 0.0),
    NSWindowStyleMaskClosable
    | NSWindowStyleMaskMiniaturizable
    | NSWindowStyleMaskResizable
    | NSWindowStyleMaskTitled,
    NSBackingStoreBuffered,
    false,
    MainThreadMarker::new(),
);
```

(Oh, fabulous [contexts and capabilities](https://tmandry.gitlab.io/blog/posts/2021-12-21-context-capabilities/), how you could relieve me of all my troubles with but the smallest of effort)!
