### ISSUE TITLE
Implementing protocol methods with `Id<_, _>` return types

### ISSUE THREAD

**Issue by ericmarkmartin** [madsmtm/objc2#317]
Suppose we have a protocol `P` with method `f(&self) -> Id<NSObject, Shared>`. If we use `declare_class!` to implement this protocol for a new type...

```rust
declare_class!(
  struct C {
    // This is unrelated to this ticket but I can't figure out how to do empty structs in `declare_class`
    filler: u8
  }

  unsafe impl ConformsTo<P> for C {
    #[method(f)]
    fn f(&self) -> Id<NSObject, Shared> {
      unimplemented!()
    }
  }
)
```

We see

`the trait `Encode` is not implemented for `icrate::objc2::rc::Id<NSObject, Shared>`

 in the macro expansion because it generates

```rust
<Id<NSObject, Shared> as $crate::encode::EncodeConvert>::__into_inner({
  $crate::panicking::panic("not implemented")
})
```
And `Id<_, _>` doesn't implement `EncodeConvert`

**Comment by madsmtm** [comment]
You can't use `#[method(f)]`, because returning `Id` requires doing extra work based on the selector, akin to `msg_send!` vs. `msg_send_id!`.

Allowing this is indeed on my todolist, see https://github.com/madsmtm/objc2/issues/282.

Until the above issue is resolved, you can return `*mut NSObject` instead.

**Comment by madsmtm** [comment]
> This is unrelated to this ticket but I can't figure out how to do empty structs in `declare_class`

This should work; though you're right, `declare_class!` should allow an empty `struct C;`.
```rust
declare_class!(
  struct C {}

  // ...
)
```
