### ISSUE TITLE
Symbols with `pid_t` missing from `header-translator` generated files

### ISSUE THREAD

**Issue by skirsdeda** [madsmtm/objc2#331]
For example `NSRunningApplication::processIdentifier` in AppKit. I guess this has smth to do with the fact that pid_t is typedef'ed.
Any way to fix this or should it be patched on case-by-case basis in icrate crates?

**Comment by skirsdeda** [comment]
Just add `"pid_t" => Self::I32,` here?: https://github.com/madsmtm/objc2/blob/master/crates/header-translator/src/rust_type.rs#L645

**Comment by skirsdeda** [comment]
Makes sense, thanks.

**Comment by madsmtm** [comment]
Not working on it right now, no, but I still intend to get it working at some point, probably as part of / after https://github.com/madsmtm/objc2/issues/345.

In the meantime you can do the following workaround yourself:
```rust
use icrate::AppKit::NSRunningApplication;
use objc2::msg_send;
use libc::pid_t;

fn application_process_identifier(app: &NSRunningApplication) -> pid_t {
    unsafe { msg_send![app, processIdentifier] }
}
```

**Comment by blu3gui7ar** [comment]
> Not working on it right now, no, but I still intend to get it working at some point, probably as part of / after #345.
> 
> In the meantime you can do the following workaround yourself:
> 
> ```rust
> use icrate::AppKit::NSRunningApplication;
> use objc2::msg_send;
> use libc::pid_t;
> 
> fn application_process_identifier(app: &NSRunningApplication) -> pid_t {
>     unsafe { msg_send![app, processIdentifier] }
> }
> ```

I am trying exact the same code, but got error about NSRunningApplication. 
Anything I am doing wrong?

```
the trait bound `&NSRunningApplication: objc2::Message` is not satisfied
the following other types implement trait `objc2::Message`:
  objc2::exception::Exception
  objc2::rc::__RcTestObject
  objc2::runtime::AnyObject
  objc2::runtime::NSObject
  objc2::runtime::ProtocolObject<P>
  objc2::runtime::__NSProxy
required for `&&NSRunningApplication` to implement `objc2::runtime::MessageReceiver`
required for `&&NSRunningApplication` to implement `MsgSend`rustc[Click for full compiler diagnostic]
```

**Comment by madsmtm** [comment]
Hmm, are you sure it's the same code? The error seems to indicate that you may have written `msg_send![&app, processIdentifier]` instead (notice the extra `&`).

**Comment by skirsdeda** [comment]
Definitely works for me, but then I'm using a bit outdated versions: 
```
objc2 = "=0.3.0-beta.4"
icrate = { version = "0.0.1", features = ["AppKit", "Foundation"] }
```

**Comment by madsmtm** [comment]
Ah yeah, I haven't released a new version of `icrate` that matches the new `objc2` version yet, see https://github.com/madsmtm/objc2/issues/537.
