### ISSUE TITLE
How to get NSObject of class?

### ISSUE THREAD

**Issue by Eliot00** [madsmtm/objc2#346]
How to get a class object like this:

```rust
        let string_class: Id<NSObject> = {
            let cls: Id<Class> = unsafe { Id::from_ptr(class("NSString")) };
            unsafe { transmute(cls) }
        };
        let classes: Id<NSArray<NSObject, Owned>> = NSArray::from_vec(vec![string_class]);
```

https://github.com/aweinstock314/rust-clipboard/blob/07d080be58a361a5bbdb548fafe9449843d968be/src/osx_clipboard.rs#L44-L48

**Comment by madsmtm** [comment]
Heh, I struggled with this _exact_ thing myself a while back, so I documented it as [an example](https://github.com/madsmtm/objc2/blob/8af9e53a903a88b8bc29f2e296c6f3eac07793cc/crates/icrate/examples/nspasteboard.rs).

In particular, I would recommend that you simply don't bother with it, and just use [`stringForType:`](https://developer.apple.com/documentation/appkit/nspasteboard/1533566-stringfortype?language=objc).

(I _am_ seeing that a made a mistake in it, `stringForType`'s return type is actually nullable, so it should be `Option<Id<NSString, Shared>>`. I should probably redo the example at some point).
