### ISSUE TITLE
Generate comments mentioning which features are needed for various items

### ISSUE THREAD

**Issue by silvanshade** [madsmtm/objc2#368]
It would be nice if we could see in the generated documentation which features are needed to use various items in the generated output. I am thinking of something along the lines of what `web-sys` does.

For example, see the entry for [`Window::document`](https://docs.rs/web-sys/latest/web_sys/struct.Window.html#method.document):

> This API requires the following crate features to be activated: `Document`, `Window`

They also link to the MDN documentation for the various APIs which is an approach we could adopt for #309.

I can try to take a look at implementing this.

**Comment by madsmtm** [comment]
Try `cargo +nightly doc --package=icrate --features=unstable-docsrs --features=[your frameworks]`, I'm pretty sure that solves most of it.

This is enabled on [docs.rs/icrate](https://docs.rs/icrate/latest/icrate/), so once I do a release things should be easy to navigate there.
