### ISSUE TITLE
Bug in leak patch: declare_class assumes msg_send is in the caller's scope

### ISSUE THREAD

**Issue by mwcampbell** [madsmtm/objc2#430]
I discovered this while trying to publish the new version of accesskit_macos, since that was the first time the crate was actually compiled with the patched objc2 release. I should update my checked-in Cargo.lock file, but it would probably also be a good idea to fix this in objc2. I guess the new release would be 0.3.0-beta.3.patch-leaks.2.

**Comment by mwcampbell** [comment]
Also, if I were to fix this entirely in AccessKit, I would have to import msg_send even though I don't directly call it, which would rightly cause a compiler warning without this bug in objc2.

**Comment by madsmtm** [comment]
Ugh, yeah, you're totally right, I've fixed this in `0.3.0-beta.3.patch-leaks.2`.
