### ISSUE TITLE
icrate: Can't instantiate `UNMutableNotificationContent` except by using `msg_send_id`

### ISSUE THREAD

**Issue by mwcampbell** [madsmtm/objc2#431]
I happen to be working on a macOS project unrelated to AccessKit, where I need to use the UserNotifications framework. I see that this framework is now exposed in icrate (thanks!), but it appears that I can't instantiate `UNMutableNotificationContent` except by using `msg_send_id`. Am I missing something?

**Comment by madsmtm** [comment]
Yeah, this is a current bug with how initializers work: Special initializers like `initWithString:` are copied from e.g. `NSString` to `NSMutableString`, but the usual initializer `init`/`new` is not.

The reason they're not yet exposed is that many classes cannot actually use the default initializer (prime example: `NSValue`). The logic behind which ones can and which ones can't is a bit complicated though so I haven't completed that yet.

**Comment by madsmtm** [comment]
But `let x: Id<UNMutableNotificationContent> = unsafe { msg_send_id![UNMutableNotificationContent, new] }` is definitely correct, and in the future `UNMutableNotificationContent::new` should be available.
