### ISSUE TITLE
Check our usage of `repr(C)` vs. `repr(transparent)`

### ISSUE THREAD

**Issue by madsmtm** [madsmtm/objc2#444]
They are slightly different, as noted in [the RFC introducing the latter](https://github.com/rust-lang/rfcs/blob/master/text/1758-repr-transparent.md)

**Comment by madsmtm** [comment]
I've verified that we don't use `#[repr(C)]` on any structs like this.

In general, ideally we'd use #[repr(transparent)] whenever possible, since it plays better with extern types once we get those, but the `improper_ctypes` lint doesn't work that well with it, so I'll keep `#[repr(C)]` for now.

**Comment by silvanshade** [comment]
> but the `improper_ctypes` lint doesn't work that well with it

I wonder if there is an issue upstream about this. Maybe worth creating one if not.

**Comment by madsmtm** [comment]
Good idea, I've opened https://github.com/rust-lang/rust/issues/115457 for that
