### ISSUE TITLE
Features that require `libc`

### ISSUE THREAD

**Issue by madsmtm** [madsmtm/objc2#500]
We kinda need to figure out a general policy on how we handle features that require `libc` (or at least just linking to it).

There are at least two things I'd like to do:
- [x] Move `MainThreadMarker` into `objc2` (with a more efficient implementation, namely [`libc::pthread_main_np`](https://docs.rs/libc/0.2.146/x86_64-apple-darwin/libc/fn.pthread_main_np.html))
  - Although really convenient, unsure if this is desired to have in `objc2`? I feel like it belongs in some lower-level library, though we don't have that, so I guess it'll have to be here.
- [x] The things gated behind `malloc` support requires `libc::free`, I'd like to remove that feature gate to be able to verify more things in `debug_assertions`. Done in https://github.com/madsmtm/objc2/pull/547.

**Comment by silvanshade** [comment]
Is there any real downside to using it?

I'm using it in the cxx-auto stuff FWIW, although that would only affect the header-translator.

**Comment by madsmtm** [comment]
Main downside is compilation speed, it's an extra dependency (with a `build.rs` script).

I'd be fine with using it in `icrate`, though also there probably behind a feature flag, again because it's an added dependency.

**Comment by madsmtm** [comment]
https://github.com/madsmtm/objc2/pull/616 changed the implementation of `MainThreadMarker` to use `pthread_main_np` and https://github.com/madsmtm/objc2/pull/625 moves it to `objc2`.
