### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by knopp** [madsmtm/objc2#533]
I just landed [this monster](https://github.com/superlistapp/super_native_extensions/pull/239). I'm having hard time expressing how happy I am to have actual types in code rather than `StrongPtr` and `id` everywhere. The number of `msg_send` calls went down from over 300 to a dozen or so. The difference in ergonomics of objc2 compared to old objc is immense. 

@madsmtm, you should consider setting up github sponsors :)

Close after reading. Thank you again.

**Comment by madsmtm** [comment]
Glad to hear that you found it useful, it's definitely nice to get an issue like this!

> should consider setting up github sponsors

Yeah, have considered it before, but I think my stance is that I do this for fun, and accepting money for it would undermine that incentive for me, making it feel more like a chore.

But I appreciate the sentiment!
