### ISSUE TITLE
unknown unexposed attribute

### ISSUE THREAD

**Issue by julian-baumann** [madsmtm/objc2#545]
I'm attempting to integrate `CoreBluetooth`, but I'm encountering the following errors while executing cargo run --bin header-translator:
```bash
│ ├─ERROR unknown unexposed attribute, name="NS_AVAILABLE_IOS", fnlike=true
│ ├─ERROR unknown unexposed attribute, name="CB_CM_API_AVAILABLE", fnlike=false
```

It appears that there may be some missing definitions. Could someone advise on how to resolve this issue?

**Comment by madsmtm** [comment]
What version of Xcode and Clang are you using?

**Comment by madsmtm** [comment]
And in any case, you should just add these in `header-translator/src/unexposed_attr.rs` since availability is exposed elsewhere.
