### ISSUE TITLE
Question: How to convert a NSEvent to a CGEvent?

### ISSUE THREAD

**Issue by pentamassiv** [madsmtm/objc2#550]
Hello and thank you for writing these crates,

I have this Swift code:

```Rust
let event1 = NSEvent.otherEvent(with: .systemDefined, location: NSPoint.zero, modifierFlags: NSEventModifierFlags(rawValue: 0xa00), timestamp: 0, windowNumber: 0, context: nil, subtype: 8, data1: (Int((code << 16 as Int32) | (0xa << 8 as Int32))), data2: -1)
event1?.cgEvent?.post(tap: .cghidEventTap)
```

and want to write the equivalent Rust code for it. This is what I have so far:

```Rust
let event = unsafe {
    AppKit::NSEvent::otherEventWithType_location_modifierFlags_timestamp_windowNumber_context_subtype_data1_data2(
        AppKit::NSEventTypeSystemDefined, // 14
        NSPoint::ZERO,
        0xb00, // NSEventModifierFlagCapsLock and NSEventModifierFlagOption
        0.0,
        0,
        None,
        8,
        (code << 16) | (0xb << 8),
        -1
    )
};
```

However, I don't understand how you can post the CGEvent with the icrate. I found [this line](https://github.com/madsmtm/objc2/blob/cf650070403feeb4619cddac528061ec8379ec23/crates/header-translator/translation-config.toml#L954) in the repo, which looks to me as if the relevant method is not generated. What is the alternative? Do I have to use the objc2 crate directly and if so, how do I do that?

**Comment by madsmtm** [comment]
> the relevant method is not generated

Indeed it isn't, yet.

The best way to use this right now is probably to use the `core-graphics` crate, and the [`CGEventRef`](https://docs.rs/core-graphics/latest/core_graphics/event/struct.CGEventRef.html) type. For some odd reason, the `CGEvent` type in that crate is marked `#[doc(hidden)]`, but you should still be able to use it.

So something like the following (you'll probably have to enable `objc2`'s `"relax-void-encoding"` feature):
```rust
unsafe fn ns_event_cg_event(event: &NSEvent) -> CGEventRef {
    let ptr: *mut c_void = unsafe { msg_send![event, CGEvent] };
    unsafe { CGEventRef::from_ptr(ptr.cast()) }
}

let cg_event = ns_event_cg_event(&event).to_owned();
cg_event.post(CGEventTapLocation::HID);
```

**Comment by pentamassiv** [comment]
Awesome, thank you for your reply. It worked. I only had to make small changes for it to compile. In case anyone else has the same problem, here is what worked for me:

```Rust
unsafe fn ns_event_cg_event(event: &NSEvent) -> &CGEventRef {
        let ptr: *mut c_void = unsafe { msg_send![event, CGEvent] };
        unsafe { CGEventRef::from_ptr(ptr.cast()) }
}

let cg_event = unsafe { Self::ns_event_cg_event(&event).to_owned() };
cg_event.post(CGEventTapLocation::HID);
```

I did have to enable objc2's `relax-void-encoding` feature
