### ISSUE TITLE
Rename icrate features to end with `_core`

### ISSUE THREAD

**Issue by madsmtm** [madsmtm/objc2#558]
Rename `Foundation` to `Foundation_core` (and similarly for the other features).

**Comment by mwcampbell** [comment]
Would this be a precursor to being able to build icrate with fewer bindings for large frameworks like AppKit? The AppKit feature currently enables several bindings that AccessKit, for example, doesn't need.

**Comment by madsmtm** [comment]
No, the proper way to do that is to do `cfg`s based on file names instead.

I remember trying to make that work before, but it's quite difficult to do with Libclang, I'm hoping to get to it once we get further with https://github.com/madsmtm/objc2/issues/345.
