### ISSUE TITLE
Support downcasting

### ISSUE THREAD

**Issue by tmandry** [madsmtm/objc2#559]
I just had to write this.. monstrosity!!

```rust
fn ns_screens(&self) -> Vec<NSScreenInfo> {
    NSScreen::screens(self.mtm)
        .iter()
        .flat_map(|s| {
            let desc = s.deviceDescription();
            let cg_id = match desc.get(ns_string!("NSScreenNumber")) {
                Some(val) if unsafe { msg_send![val, isKindOfClass:NSNumber::class() ] } => {
                    let number: &NSNumber = unsafe { std::mem::transmute(val) }; // :(
                    number.as_u32()
                }
                val => {
                    warn!(
                        "Could not get NSScreenNumber for screen with name {:?}: {:?}",
                        unsafe { s.localizedName() },
                        val,
                    );
                    return None;
                }
            };
            Some(NSScreenInfo {
                frame: s.frame(),
                visible_frame: s.visibleFrame(),
                cg_id,
            })
        })
        .collect()
}
```

<details>
<summary>Original attempt (segfault)</summary>

```rust
fn ns_screens(&self) -> Vec<NSScreenInfo> {
    NSScreen::screens(self.mtm)
        .iter()
        .flat_map(|s| {
            let value = s
                .deviceDescription()
                .get(ns_string!("NSScreenNumber"))
                .map(|val: &AnyObject| -> &'_ CFType { unsafe { std::mem::transmute(val) } });
            //  oh, nooo                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
            let number = value.and_then(|v| v.downcast::<CFNumber>());
            let Some(cg_id) = number else {
                return None;
            };
            Some(NSScreenInfo {
                frame: s.frame(),
                visible_frame: s.visibleFrame(),
                cg_id: cg_id.to_i32().unwrap().try_into().unwrap(), // :(
            })
        })
        .collect()
}
```

`CFType` and `CFNumber` are from `core_foundation`, which supports downcasting via type id. Its CFNumber interface is weirdly incomplete though, hence all the unwraps.

EDIT: I thought this would work because of toll-free bridging, but it segfaults. So I went with the approach in #474, which is a bit nicer.
</details>

I see this is being worked on in #474 but thought this would lend some motivation.

Thanks for your work on this crate!

**Comment by madsmtm** [comment]
Heh, yeah, I have to do that dance in Winit too, honestly it's mostly because the `deviceDescription` API is terrible.

But I hear what you're saying, and will probably use this issue to track progress, instead of the PR.

> I thought this would work because of toll-free bridging, but it segfaults

Yeah, that's because you used the wrong `core-foundation` type; you can't convert to `&'_ CFType`, that is basically the same as `&Id<AnyObject>` - instead, you should've returned `CFType` directly, but done the conversion using something like `CFType::wrap_under_get_rule(val as *const AnyObject as *const c_void)` (`core-foundation` doesn't actually seem to expose a way to do this without the extra retain/release).

**Comment by madsmtm** [comment]
This has (finally) been fixed in https://github.com/madsmtm/objc2/pull/474, the inner part of your example can now be written safely as:

```rust
let desc = s.deviceDescription();
let cg_id = match desc.get(ns_string!("NSScreenNumber")).map(|number| number.downcast::<NSNumber>()) {
    Some(Ok(val)) => number.as_u32(),
    val => {
        warn!(
            "Could not get NSScreenNumber for screen with name {:?}: {:?}",
            unsafe { s.localizedName() },
            val,
        );
        return None;
    }
};
```

**Comment by tmandry** [comment]
That's.. _much_ better, thank you!!
