### ISSUE TITLE
Generating Objective-C bindings to Rust-declared ObjC classes

### ISSUE THREAD

**Issue by chyyran** [madsmtm/objc2#583]
Hi, I'm looking to *export* an Objective-C API that deals with `id` and protocol objects. Things seem to work great within Rust land and my crate is using `icrate` and `objc` definitions, everything works very well but I'd like to expose my functionality to non-Rust users building their apps with Swift or Objective-C.

I first thought about writing a C API, but taking `*const ProtocolObject<dyn T>` for example didn't seem like the correct approach. Is there a way to export an objective-C API from Rust?

**Comment by madsmtm** [comment]
Hmm, are you defining your own classes with `declare_class!`, or just consuming Objective-C objects?

**Comment by madsmtm** [comment]
As an example, you could fairly easily export a function that takes Objective-C types. If you would like to return objects to Objective-C, it's a bit more complicated as then you have to deal with memory management rules, but it should also be doable.

```rust
// foo.rs

#[no_mange]
extern "C" fn my_function(obj: &AnyObject, protocol_obj: &ProtocolObject<dyn NSCopying>) {
    println!("{obj:?} {protocol_obj:?}");
}
```

```c
// foo.c
void my_function(id obj, id<NSCopying> protocol_obj);
```

**Comment by madsmtm** [comment]
Maybe I can make things a bit more clear with a table:

| Objective-C     | Rust argument                    | Rust return                         |
|-----------------|----------------------------------|-------------------------------------|
| `id`            | `&AnyObject`                     | `Id<AnyObject>`                     |
| `id<NSCopying>` | `&ProtocolObject<dyn NSCopying>` | `Id<ProtocolObject<dyn NSCopying>>` |
| `NSObject*`     | `&NSObject`                      | `Id<NSObject>`                      |
| `Class`         | `&AnyClass`                      | `&'static AnyClass`                 |

**Comment by chyyran** [comment]
Thanks, that table is very useful. I was able to just publish regular C headers that take `id<T>`.
