### ISSUE TITLE
NSAttributedString::initWithString_attributes has the wrong type &NSDictionary<NSString>

### ISSUE THREAD

**Issue by eks5115** [madsmtm/objc2#605]
```rust
let dict = NSDictionary::from_vec(
    &[&*NSString::from_str("NSForegroundColorAttributeName")],
    vec![NSColor::whiteColor()]
);
let attr_title = NSAttributedString::initWithString_attributes(NSAttributedString::alloc(), &title, Some(dict.as_ref()));
button.setAttributedTitle(&attr_title);
```

42  |             let a_title = NSAttributedString::initWithString_attributes(NSAttributedString::alloc(), &title, Some(dict.as_ref()));
    |                                                                                                              ---- ^^^^^^^^^^^^^ expected `&NSDictionary<NSString>`, found `&NSDictionary<NSString, NSColor>`
    |                                                                                                              |
    |                                                                                                              arguments to this enum variant are incorrect

**Comment by madsmtm** [comment]
You have to downcast the `NSColor` to `AnyObject` before passing it to the function:
```rust
vec![Id::as_super(Id::as_super(NSColor::whiteColor()))]
```

**Comment by madsmtm** [comment]
Which, I know, isn't pretty, but that's how it works currently

**Comment by eks5115** [comment]
thank you!

**Comment by eks5115** [comment]
sdf
