### ISSUE TITLE
Some suggestions regarding objc2-foundation and block2

### ISSUE THREAD

**Issue by libark** [madsmtm/objc2#615]
1. When using NSArray or NSDictionary, their values are usually generic types, so they need to be defined using AnyObject, such as `NSMutableDictionary::<NSString, AnyObject>`. However, for types like NSNumber, multiple calls to `into_super `or unsafe methods such as `Id::cast` are required to convert them to AnyObject. Considering the frequency of this operation, could a safe method be provided to complete the conversion from NSNumber to AnyObject in one step?

2. When using many Apple frameworks, it is necessary to pass the static CFString exported from the framework to NSString. Could a method be added for NSString, create NString from a raw pointer?

3. When using block2, all parameter and return value types must implement Encode trait, but many Apple frameworks do not use Objective-C interfaces and types. Could a feature be added to block2 to allow it to be used in C interface framework wrappers, replace block?

**Comment by madsmtm** [comment]
I've added documentation on interop with `core-foundation` in eb39164bcf67c8e8328cfe493b7be37a9e5101a7

**Comment by madsmtm** [comment]
Again, thanks for the review. I'll close this, and consider the remaining items as tracked by https://github.com/madsmtm/objc2/issues/518 and https://github.com/madsmtm/objc2/issues/556.
