### ISSUE TITLE
How to convert UIImage to AnyObject in ideal way?

### ISSUE THREAD

**Issue by AllenDang** [madsmtm/objc2#649]
I'm creating a share image function, and need to create a `Id<NSArray<AnyObject>>` and pass it to `UIActivityViewController::initWithActivityItems_applicationActivities`.

Currently I use 
```rust
let shared_items: Id<NSArray<AnyObject>> = NSArray::from_vec(vec![std::mem::transmute(ui_image)])
```

to convert Retained<UIImage> to AnyObject. I feel this might not the right way to do.

Is there any ideal way to convert Retained<UIImage> to AnyObject?

**Comment by madsmtm** [comment]
You can do:
```rust
let obj = Retained::into_super(Retained::into_super(ui_image));
let shared_items: Retained<NSArray<AnyObject>> = NSArray::from_vec(vec![obj]);
```

Though I agree that it's ugly that you have to call `into_super` twice, I'm working on making it better in https://github.com/madsmtm/objc2/issues/518.
