### ISSUE TITLE
`objc2-media-player`: `MPMusicPlayerController::nowPlayingItem()` always returns first returned value

### ISSUE THREAD

**Issue by valentinegb** [madsmtm/objc2#650]
Running `MPMusicPlayerController::nowPlayingItem()` in a loop, the first iteration accurately reflects the actually playing media item. However, all iterations after that will return the same thing, even if it's not longer accurate.

![Screenshot 2024-09-15 at 3 16 10 PM](https://github.com/user-attachments/assets/023d4c0a-7c88-4598-910c-2889f58f759a)

Minimal reproducible example: [objc2-media-player-mre.zip](https://github.com/user-attachments/files/17007600/objc2-media-player-mre.zip)

**Comment by madsmtm** [comment]
Not really familiar with MediaPlayer, but my first guess is that you have to be running the main event loop, you cannot just busy loop like this.

Try launching the application with `NSApplicationMain`, and use a `NSTimer` to periodically check the value?

**Comment by valentinegb** [comment]
Sorry, I'm not very familiar with Apple's Objective C frameworks, specifically the Foundation framework. I would assume `NSApplicationMain` is a structure in the `objc2-foundation` crate, but I can't find it.

**Comment by madsmtm** [comment]
My apologies, I was tired when I wrote that, should've been more thorough in my explanation.

I have added some general documentation on run loops in [here](https://github.com/madsmtm/objc2/blob/6b723f761448f316d2bdd29db78936474ccfad50/crates/objc2/src/topics/run_loop.md), please check that out, and tell me if things are still unclear?

I think that even with that, things won't work for you unless you also add the [`NSAppleMusicUsageDescription`](https://developer.apple.com/documentation/bundleresources/information_property_list/nsapplemusicusagedescription) to your `Info.plist`. How to do so nicely isn't really figured out in the Rust ecosystem yet, I suspect you'll have to manually create a bundle, though you may be able to get away with using [`embed_plist`](https://docs.rs/embed_plist/).

**Comment by valentinegb** [comment]
```rs
use objc2_foundation::{NSDate, NSRunLoop};
use objc2_media_player::MPMusicPlayerController;

fn main() {
    unsafe {
        let run_loop = NSRunLoop::currentRunLoop();
        let mut date = NSDate::now();

        loop {
            date = date.dateByAddingTimeInterval(0.001);

            run_loop.runUntilDate(&date);

            let music_player = MPMusicPlayerController::systemMusicPlayer();

            if let Some(now_playing_item) = music_player.nowPlayingItem() {
                println!(
                    "now playing {} by {}",
                    now_playing_item.title().unwrap(),
                    now_playing_item.artist().unwrap(),
                );
            } else {
                println!("nothing is playing now");
            }
        }
    }
}
```

This does seem to work! Is there a way I could not have to specify a date though, and just have each iteration run whenever the previous iteration is finished?

**Comment by madsmtm** [comment]
I think `runMode_beforeDate(NSDefaultRunLoopMode, &NSDate::distantPast())` would do that, see [the docs](https://developer.apple.com/documentation/foundation/nsrunloop/1411525-runmode?language=objc). That will consume 100% CPU though, FYI. If you want to just listen for changes to the `nowPlayingItem`, I think you have to use KVO, see [my introduction here](https://github.com/madsmtm/objc2/blob/6b723f761448f316d2bdd29db78936474ccfad50/crates/objc2/src/topics/kvo.md).
