### ISSUE TITLE
`MTLResourceID` should expose `_impl`

### ISSUE THREAD

**Issue by Jasper-Bekkers** [madsmtm/objc2#660]
For FFI reasons its often useful to be able to get access to the raw value, at the moment I'm just transmuting the struct back and forth but nicer would be to have a `to_raw() -> u64`

**Comment by madsmtm** [comment]
I believe our generation is correct here in hiding the field, that's also what [Apple's docs](https://developer.apple.com/documentation/metal/mtlresourceid?language=objc) show.

But the again, Swift's generation [still allows constructing it with the private name](https://developer.apple.com/documentation/metal/mtlresourceid/3974158-init).

I suspect that's a bug in Swift's generation though, private fields seems like a fairly rare case, [I only found three in our currently generated files](https://github.com/madsmtm/objc2-generated/commit/5889b4326e1dbac241422924d09ae615c413c681)?

---

Anyhow, I'm fine with exposing `from_raw` and `to_raw`, though I think `from_raw` would have to be `unsafe`, from reading the docs on `MTLResourceID`:
> A MTLResourceID represents a specific GPU resource, mutating this handle is undefined unless the mutation results in the value equalling an already existing handle of the same resource type.

I don't actually know if that's correct, haven't used this API myself and not too familiar with Metal, what do you think?

**Comment by Jasper-Bekkers** [comment]
> I believe our generation is correct here in hiding the field, that's also what [Apple's docs](https://developer.apple.com/documentation/metal/mtlresourceid?language=objc) show.

I think so too, there are some apple provided libraries though that access the field directly. (Metal Shader Converter), which is why we need it in our saxaboom crate.

> But the again, Swift's generation [still allows constructing it with the private name](https://developer.apple.com/documentation/metal/mtlresourceid/3974158-init). I suspect that's a bug in Swift's generation though, private fields seems like a fairly rare case, [I only found three in our currently generated files](https://github.com/madsmtm/objc2-generated/commit/5889b4326e1dbac241422924d09ae615c413c681)?
> 
> ---
> 
> Anyhow, I'm fine with exposing `from_raw` and `to_raw`, though I think `from_raw` would have to be `unsafe`, from reading the docs on `MTLResourceID`:
> > A MTLResourceID represents a specific GPU resource, mutating this handle is undefined unless the mutation results in the value equalling an already existing handle of the same resource type.
> 
> I don't actually know if that's correct, haven't used this API myself and not too familiar with Metal, what do you think?
> 

I don't mind marking from_raw as unsafe, and I've done similar for similar constructs in our engine.

**Comment by MarijnS95** [comment]
@madsmtm for completeness Apple "exposes" and "uses" it here in their IRConverter runtime headers:

https://github.com/Traverse-Research/saxaboom/blob/2217a09e84e842e75231c5817bb94f7545577d6c/bindings_generator/vendor/metal_irconverter_runtime/metal_irconverter_runtime.h#L79

https://github.com/Traverse-Research/saxaboom/blob/2217a09e84e842e75231c5817bb94f7545577d6c/bindings_generator/vendor/metal_irconverter_runtime/metal_irconverter_runtime.h#L657-L660
