### ISSUE TITLE
Translate Screen Saver framework

### ISSUE THREAD

**Issue by valentinegb** [madsmtm/objc2#665]
Would it be reasonable to translate the [Screen Saver](https://developer.apple.com/documentation/screensaver) framework? I haven't touched it yet, so I don't know, but it'd be nice to be able to use Rust, my preferred language, instead of Objective-C or Swift.

**Comment by madsmtm** [comment]
Done in 8852b5d3e7e7bbf6959c0f7f80d358adabaaca58, will release it as part of the next big release
