### ISSUE TITLE
Trying to contribute OpenDirectory framework

### ISSUE THREAD

**Issue by sheagcraig** [madsmtm/objc2#673]
Hi! Awesome project that I'm just discovering. I'm working on a project that needs the OpenDirectory framework and I thought I'd take a crack at contributing that.

I added a new workspace crate to `/framework-crates/objc2-open-directory` and filled in the `translation-config.toml` as follows:

```toml
framework = "OpenDirectory"
crate = "objc2-open-directory"
required-dependencies = ["objc2-foundation"]
macos = "10.6"
maccatalyst = "13.0"
```

I have Xcode 16.1 with the macOS 15.1 platform support available.

On running `cargo run --bin header-translator -- /Applications/Xcode.app/Contents/Developer` header-translator starts to get really angry with me:

```
│ ├─ERROR expected module to be available in library, location=Location { path_components: ["OpenDirectory", "CFOpenDirectory"] }
│ ├─ERROR expected module to be available in library, location=Location { path_components: ["OpenDirectory", "CFOpenDirectory", "CFOpenDirectoryConstants"] }
│ ├─ERROR unknown unexposed attribute, name="__OSX_AVAILABLE_BUT_DEPRECATED_MSG", fnlike=true
│ ├─ERROR unknown unexposed attribute, name="__OSX_AVAILABLE_BUT_DEPRECATED_MSG", fnlike=true
│ ├─ERROR unknown unexposed attribute, name="__OSX_AVAILABLE_BUT_DEPRECATED_MSG", fnlike=true
│ ├─ERROR unknown unexposed attribute, name="__OSX_AVAILABLE_BUT_DEPRECATED_MSG", fnlike=true
│ ├─ERROR expected module to be available in library, location=Location { path_components: ["OpenDirectory", "CFOpenDirectory", "CFODContext"] }
│ ├─ERROR expected module to be available in library, location=Location { path_components: ["OpenDirectory", "CFOpenDirectory", "CFODNode"] }
│ ├─ERROR unknown attribute, attr=ReturnsRetained
│ ├─ERROR unknown attribute, attr=ReturnsRetained
│ ├─ERROR unknown unexposed attribute, name="__OSX_AVAILABLE_BUT_DEPRECATED_MSG", fnlike=true
│ ├─ERROR unknown unexposed attribute, name="__OSX_AVAILABLE_BUT_DEPRECATED_MSG", fnlike=true
│ ├─ERROR unknown unexposed attribute, name="__OSX_AVAILABLE_BUT_DEPRECATED_MSG", fnlike=true
│ ├─ERROR unknown unexposed attribute, name="__OSX_AVAILABLE_BUT_DEPRECATED_MSG", fnlike=true
│ ├─ERROR unknown attribute, attr=ReturnsRetained
│ ├─ERROR expected module to be available in library, location=Location { path_components: ["OpenDirectory", "CFOpenDirectory", "CFODQuery"] }
```

There's more, but figured I'd start there. Can you give me a nudge in the right direction?

**Comment by madsmtm** [comment]
The `unknown unexposed attribute` ones are easy, should be enough to add them to `crates/header-translator/src/unexposed_attr.rs`.

I am unsure of the `expected module to be available in library`, might be because OpenDirectory re-exports `CFOpenDirectory` too? And I don't think `header-translator` properly supports that at the moment.

See also https://github.com/madsmtm/objc2/issues/640, I think we might need that to be resolved before OpenDirectory is possible?

**Comment by sheagcraig** [comment]
Ahhh. Thanks-that makes sense. I'll hold tight until that umbrella issue is worked out.

**Comment by madsmtm** [comment]
I went ahead and added the framework myself in 0ee4d689a617304bded51a7eb65d0d70464c8536, thanks for the input!
