### ISSUE TITLE
`microphone`is missing in `SCStreamOutputType`.

### ISSUE THREAD

**Issue by yujonglee** [madsmtm/objc2#682]
We only have `screen` and `audio` here.
https://docs.rs/objc2-screen-capture-kit/latest/objc2_screen_capture_kit/struct.SCStreamOutputType.html

`microphone` is recently added.
https://developer.apple.com/documentation/screencapturekit/scstreamoutputtype/microphone

**Comment by madsmtm** [comment]
It's available on `master`: https://github.com/madsmtm/objc2-generated/blob/82f7f3b1d3746092c638bbe93ff9f10317a78130/ScreenCaptureKit/SCStream.rs#L27.

Which I'll be releasing _fairly_ soon (see [the milestone](https://github.com/madsmtm/objc2/milestone/6)).
